import { shuffle } from '../utils';

export const SKILLS = shuffle([
  {name: 'Agile', link: 'http://agilemanifesto.org/'},
  {name: 'Angular', link: 'https://angular.io/'},
  {name: 'AWS', link: 'https://aws.amazon.com/'},
  {name: 'Bootstrap', link: 'https://getbootstrap.com/'},
  {name: 'CD', link: 'https://continuousdelivery.com/'},
  {name: 'CI', link: 'http://searchsoftwarequality.techtarget.com/definition/continuous-integration'},
  {name: 'CSS', link: 'https://developer.mozilla.org/en-US/docs/Web/CSS'},
  {name: 'Data science', link: 'http://blog.alexa.com/know-data-science-important/'},
  {name: 'Django', link: 'https://www.djangoproject.com/'},
  {name: 'Docker', link: 'https://www.docker.com/'},
  {name: 'DRF', link: 'http://www.django-rest-framework.org/'},
  {name: 'GIT', link: 'https://git-scm.com/'},
  {name: 'gulp', link: 'http://gulpjs.com/'},
  {name: 'HTML 5', link: 'https://en.wikipedia.org/wiki/HTML5'},
  {name: 'JavaScript', link: 'https://www.javascript.com/'},
  {name: 'JQuery', link: 'https://jquery.com/'},
  {name: 'Linux', link: 'https://www.linux.com/what-is-linux'},
  {name: 'Matplotlib', link: 'http://matplotlib.org/'},
  {name: 'MySQL', link: 'https://www.mysql.com/'},
  {name: 'Pandas', link: 'http://pandas.pydata.org/'},
  {name: 'plotly', link: 'https://plot.ly/'},
  {name: 'PostgreSQL', link: 'https://www.postgresql.org/'},
  {name: 'Python', link: 'https://www.python.org/about/'},
  {name: 'REST', link: 'http://www.restapitutorial.com/lessons/whatisrest.html'},
  {name: 'SASS', link: 'http://sass-lang.com/'},
  {name: 'TDD', link: 'http://agiledata.org/essays/tdd.html'},
  {name: 'TypeScript', link: 'https://www.typescriptlang.org/'},
]);
